//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADFSDPhamaV2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int med { get; set; }
        public int quantity { get; set; }
    
        public virtual Medication Medication { get; set; }
    }
}
